namespace Craiel.Essentials.Enums
{
    using System.Collections.Generic;
    using System.Linq;
    using Utils;

    public static class EnumValues
    {
        // -------------------------------------------------------------------
        // Auto Generated by EnumValues.tt DO NOT MODIFY DIRECTLY!
        // -------------------------------------------------------------------
        public static readonly IList<DelayedLoadedObjectPhase> DelayedLoadedObjectPhaseValues = EnumDef<DelayedLoadedObjectPhase>.Values.ToList();

        public static readonly IList<SceneRootCategory> SceneRootCategoryValues = EnumDef<SceneRootCategory>.Values.ToList();

        public static readonly IList<SceneTransitionStep> SceneTransitionStepValues = EnumDef<SceneTransitionStep>.Values.ToList();

        public static readonly IList<TelegramReturnReceiptStatus> TelegramReturnReceiptStatusValues = EnumDef<TelegramReturnReceiptStatus>.Values.ToList();

        public static readonly IList<YamlContainerType> YamlContainerTypeValues = EnumDef<YamlContainerType>.Values.ToList();

        public static readonly IList<GameLanguage> GameLanguageValues = EnumDef<GameLanguage>.Values.ToList();
    }
}
