namespace Craiel.Essentials.Enums
{
    using System.Collections.Generic;
    using System.Linq;
    using Utils;

    public static class EnumValues
    {
        // -------------------------------------------------------------------
        // Auto Generated by EnumValues.tt DO NOT MODIFY DIRECTLY!
        // -------------------------------------------------------------------
        public static readonly IList<DelayedLoadedObjectPhase> DelayedLoadedObjectPhaseValues = EnumDefInt<DelayedLoadedObjectPhase>.Values.ToList();

        public static readonly IList<SceneRootCategory> SceneRootCategoryValues = EnumDefInt<SceneRootCategory>.Values.ToList();

        public static readonly IList<SceneTransitionStep> SceneTransitionStepValues = EnumDefInt<SceneTransitionStep>.Values.ToList();

        public static readonly IList<TelegramReturnReceiptStatus> TelegramReturnReceiptStatusValues = EnumDefInt<TelegramReturnReceiptStatus>.Values.ToList();

        public static readonly IList<YamlContainerType> YamlContainerTypeValues = EnumDefInt<YamlContainerType>.Values.ToList();

        public static readonly IList<GameLanguage> GameLanguageValues = EnumDefInt<GameLanguage>.Values.ToList();
    }
}
