namespace Craiel.Essentials.Enums
{
    using System.Collections.Generic;
    using System.Linq;

    public static class EnumValues
    {
        // -------------------------------------------------------------------
        // Auto Generated by EnumValues.tt DO NOT MODIFY DIRECTLY!
        // -------------------------------------------------------------------
        public static readonly IList<DelayedLoadedObjectPhase> DelayedLoadedObjectPhaseValues = EnumCache<DelayedLoadedObjectPhase>.Values.ToList();

        public static readonly IList<SceneRootCategory> SceneRootCategoryValues = EnumCache<SceneRootCategory>.Values.ToList();

        public static readonly IList<SceneTransitionStep> SceneTransitionStepValues = EnumCache<SceneTransitionStep>.Values.ToList();

        public static readonly IList<TelegramReturnReceiptStatus> TelegramReturnReceiptStatusValues = EnumCache<TelegramReturnReceiptStatus>.Values.ToList();

        public static readonly IList<YamlContainerType> YamlContainerTypeValues = EnumCache<YamlContainerType>.Values.ToList();

        public static readonly IList<GameLanguage> GameLanguageValues = EnumCache<GameLanguage>.Values.ToList();
    }
}
